#!/usr/bin/env python3
"""Bounded stock-client qualification for the five M2 mutation tools.

Preparation is Docker-free.  ``--run`` is an explicit, serialized runtime gate.
The harness executes no project-supplied host command and never installs software.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import selectors
import shutil
import signal
import subprocess
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WORK = ROOT / "target/m2-clients"
ARTIFACTS = ROOT / "docs/validation/m2-clients"
RECEIPT = ROOT / "docs/validation/M2-clients.json"
NODE = Path("/Users/cburgosro/.nvm/versions/node/v24.15.0/bin/node")
INSPECTOR = ROOT / "target/m1-17-inspector/node_modules/@modelcontextprotocol/inspector/clients/cli/build/index.js"
INSPECTOR_PACKAGE = ROOT / "target/m1-17-inspector/node_modules/@modelcontextprotocol/inspector/package.json"
CLAUDE = Path("/Users/cburgosro/.local/bin/claude")
SERVER = ROOT / "target/release/rust-engineering-mcp"
DOCKER = Path("/Applications/Docker.app/Contents/Resources/bin/docker")
IMAGE = "sha256:8fac70723a8d04b6ec9633ab721806b8a55f4f083a1b3f988c61bf6a00fa1909"
VENDOR_FP = "sha256:743947d5788c1a4385a4b59869c5b8bd0535f7fc0d875b51288f9b26b2d0eba1"
MODEL = "claude-sonnet-5"
EFFORT = "medium"
MAX_OUTPUT = 8 * 1024 * 1024
WALL_SECONDS = 900

M1_SNAPSHOTS = {
    "rust.project.open": "project-open-tool.json",
    "rust.project.inspect": "project-inspect-tool.json",
    "rust.toolchain.inspect": "toolchain-inspect-tool.json",
    "rust.check": "check-tool.json",
    "rust.fmt.check": "format-tool.json",
    "rust.clippy": "clippy-tool.json",
    "rust.test": "test-tool.json",
    "rust.dependencies.audit": "audit-tool.json",
    "rust.diagnostics.explain": "explain-tool.json",
    "rust.quality.gate": "quality-tool.json",
    "rust.catalog.status": "catalog-status-tool.json",
    "rust.crate.search": "crate-search-tool.json",
    "rust.crate.inspect": "crate-inspect-tool.json",
}
M2_TOOLS = (
    "rust.manifest.patch",
    "rust.fmt.apply",
    "rust.fix.apply",
    "rust.dependency.add",
    "rust.dependency.remove",
)
EXPECTED_TOOLS = tuple(M1_SNAPSHOTS) + M2_TOOLS

INITIAL_MANIFEST = b'''[package]
name = "m2_client_probe"
version = "0.1.0"
edition = "2024"

[dependencies]
'''
FINAL_MANIFEST = INITIAL_MANIFEST + b'''\n[lints.rust]
unsafe_code = "forbid"
'''
LOCK = b'''# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "m2_client_probe"
version = "0.1.0"
'''
INITIAL_SOURCE = b"pub fn answer( )->u8{let mut value=42;value}\n"
FINAL_SOURCE = b'''pub fn answer() -> u8 {
    let value = 42;
    value
}
'''


def sha_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def sha_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(65536), b""):
            digest.update(block)
    return digest.hexdigest()


def canonical(value: object) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode()


def save_json(path: Path, value: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n")


def safe_environment(home: Path) -> dict[str, str]:
    environment = {
        # Claude's installed OAuth/keychain login is part of its normal model API.
        # Restricted mode, empty setting sources, strict MCP config and no builtins
        # prevent that account home from becoming model-visible workspace context.
        "HOME": os.environ["HOME"],
        "PATH": "/Users/cburgosro/.local/bin:/Users/cburgosro/.nvm/versions/node/v24.15.0/bin:/usr/bin:/bin:/usr/sbin:/sbin",
        "TMPDIR": str(home / "tmp"),
        "LANG": "en_US.UTF-8",
    }
    for name in ("USER", "LOGNAME", "SHELL"):
        if name in os.environ:
            environment[name] = os.environ[name]
    return environment


def run_bounded(
    argv: list[str], cwd: Path, environment: dict[str, str], timeout: int, artifact: Path
) -> tuple[int, bytes, bytes, float]:
    started = time.monotonic()
    child = subprocess.Popen(
        argv,
        cwd=cwd,
        env=environment,
        stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        start_new_session=True,
    )
    selector = selectors.DefaultSelector()
    buffers = {"stdout": bytearray(), "stderr": bytearray()}
    total = 0
    failure = None
    failed_at = None
    deadline = started + timeout
    for name, pipe in (("stdout", child.stdout), ("stderr", child.stderr)):
        os.set_blocking(pipe.fileno(), False)
        selector.register(pipe, selectors.EVENT_READ, name)
    while child.poll() is None or selector.get_map():
        now = time.monotonic()
        if failure is None and now >= deadline:
            failure = "command_timeout"
            failed_at = now
            try:
                os.killpg(child.pid, signal.SIGKILL)
            except ProcessLookupError:
                pass
        for key, _ in selector.select(0.05):
            try:
                block = os.read(key.fileobj.fileno(), 65536)
            except BlockingIOError:
                continue
            if not block:
                selector.unregister(key.fileobj)
                key.fileobj.close()
                continue
            total += len(block)
            remaining = max(0, MAX_OUTPUT - sum(len(value) for value in buffers.values()))
            buffers[key.data].extend(block[:remaining])
            if failure is None and total > MAX_OUTPUT:
                failure = "command_output_limit"
                failed_at = time.monotonic()
                try:
                    os.killpg(child.pid, signal.SIGKILL)
                except ProcessLookupError:
                    pass
        if failure is not None and child.poll() is not None and not selector.get_map():
            break
        if failed_at is not None and time.monotonic() - failed_at >= 10:
            for registered in list(selector.get_map().values()):
                selector.unregister(registered.fileobj)
                registered.fileobj.close()
            break
    selector.close()
    child.wait()
    stdout, stderr = bytes(buffers["stdout"]), bytes(buffers["stderr"])
    duration = time.monotonic() - started
    artifact.parent.mkdir(parents=True, exist_ok=True)
    artifact.with_suffix(".stdout").write_bytes(stdout)
    artifact.with_suffix(".stderr").write_bytes(stderr)
    save_json(
        artifact,
        {
            "argv": argv,
            "exit_code": child.returncode,
            "duration_seconds": round(duration, 3),
            "stdout_bytes": len(stdout),
            "stdout_sha256": sha_bytes(stdout),
            "stderr_bytes": len(stderr),
            "stderr_sha256": sha_bytes(stderr),
            "status": "failed" if failure else "complete",
            "failure": failure,
            "observed_output_bytes": total,
        },
    )
    if failure is not None:
        raise RuntimeError(failure)
    return child.returncode, stdout, stderr, duration


def copy_vendor(destination: Path) -> None:
    source = ROOT / "fixtures/cargo-vendor-data/vendor"
    shutil.copytree(source, destination, symlinks=False)
    for item in destination.rglob("*"):
        if item.is_symlink() or not (item.is_dir() or item.is_file()):
            raise RuntimeError("vendor_special_entry")


def create_fixture(run: Path) -> dict[str, Path]:
    project = run / "project"
    state = run / "state"
    home = run / "home"
    for directory in (project / "src", state, home / "tmp"):
        directory.mkdir(parents=True, mode=0o700)
    (project / "Cargo.toml").write_bytes(INITIAL_MANIFEST)
    (project / "Cargo.lock").write_bytes(LOCK)
    (project / "src/lib.rs").write_bytes(INITIAL_SOURCE)
    vendor = run / "vendor"
    copy_vendor(vendor)
    return {"project": project, "state": state, "home": home, "vendor": vendor}


def snapshot(root: Path) -> dict[str, str]:
    result = {}
    for path in sorted(root.rglob("*")):
        if path.is_symlink():
            raise RuntimeError("fixture_symlink")
        if path.is_file():
            result[str(path.relative_to(root))] = sha_file(path)
    return result


def server_args(paths: dict[str, Path], socket: str, grants: bool) -> list[str]:
    arguments = [
        "serve", "--stdio", "--root", str(paths["project"]),
        "--docker", str(DOCKER), "--docker-socket", socket,
        "--state-root", str(paths["state"]), "--rust-image", IMAGE,
    ]
    if grants:
        for flag in (
            "--allow-manifest-write", "--allow-fmt-write", "--allow-fix-write",
            "--allow-dependency-add", "--allow-dependency-remove",
        ):
            arguments += [flag, str(paths["project"])]
        arguments += [
            "--cargo-vendor-dir", str(paths["vendor"]),
            "--cargo-vendor-tree-sha256", VENDOR_FP,
        ]
    return arguments


def inspector_call(
    run: Path,
    environment: dict[str, str],
    label: str,
    args: list[str],
    method: str,
    tool: str | None = None,
    tool_args: dict | None = None,
    deadline: float | None = None,
    expected_tool_error: bool = False,
) -> dict:
    argv = [str(NODE), str(INSPECTOR), str(SERVER), *args, "--", "--method", method,
            "--format", "json", "--stored-auth-only"]
    if method == "tools/list":
        argv.append("--strict")
    if tool is not None:
        argv += ["--tool-name", tool, "--tool-args-json", json.dumps(tool_args, separators=(",", ":"))]
    remaining = 180 if deadline is None else min(180, int(deadline - time.monotonic()))
    if remaining < 1:
        raise RuntimeError("qualification_wall_timeout")
    code, stdout, _, _ = run_bounded(argv, run, environment, remaining, ARTIFACTS / f"inspector-{label}.json")
    expected_code = 5 if expected_tool_error else 0
    if code != expected_code:
        raise RuntimeError(f"inspector_{label}_exit_{code}")
    response = json.loads(stdout)
    if expected_tool_error:
        result = response.get("result", response)
        if not isinstance(result, dict) or result.get("isError") is not True:
            raise RuntimeError(f"inspector_{label}_missing_tool_error")
    return response


def structured(result: dict) -> dict:
    value = result.get("result", result)
    content = value.get("structuredContent") if isinstance(value, dict) else None
    if not isinstance(content, dict):
        raise RuntimeError("missing_structured_content")
    return content


def inspect_stock_client(run: Path, paths: dict[str, Path], socket: str, deadline: float) -> dict:
    environment = safe_environment(paths["home"])
    denied_args = server_args(paths, socket, False)
    discovery = inspector_call(run, environment, "discovery", denied_args, "tools/list", deadline=deadline)
    tools = discovery.get("result", discovery).get("tools")
    if not isinstance(tools, list) or [tool.get("name") for tool in tools] != list(EXPECTED_TOOLS):
        raise RuntimeError("inspector_tool_inventory")
    by_name = {tool["name"]: tool for tool in tools}
    snapshot_dir = ROOT / "crates/mcp-server/tests/snapshots"
    unchanged = {}
    for name, filename in M1_SNAPSHOTS.items():
        expected = json.loads((snapshot_dir / filename).read_text())
        if by_name[name] != expected:
            raise RuntimeError(f"m1_snapshot_changed_{name}")
        unchanged[name] = sha_bytes(canonical(expected))
    opened = inspector_call(
        run, environment, "open", denied_args, "tools/call", "rust.project.open",
        {"path": str(paths["project"])}, deadline=deadline,
    )
    if structured(opened).get("status") != "passed":
        raise RuntimeError("inspector_open_failed")
    fake_ref = "prj_" + "0" * 32
    fake_fp = "sha256:" + "0" * 64
    calls = {
        "rust.manifest.patch": {"project_ref": fake_ref, "action": {"mode": "preview", "expected_project_fingerprint": fake_fp, "edit": {"operation": "lint_set", "scope": "package", "tool": "rust", "name": "unsafe_code", "level": "forbid", "priority": 0}}},
        "rust.fmt.apply": {"project_ref": fake_ref, "action": {"mode": "preview", "expected_project_fingerprint": fake_fp}},
        "rust.fix.apply": {"project_ref": fake_ref, "action": {"mode": "preview", "expected_project_fingerprint": fake_fp}},
        "rust.dependency.add": {"project_ref": fake_ref, "action": {"mode": "preview", "expected_project_fingerprint": fake_fp, "name": "quote", "requirement": "=1.0.47"}},
        "rust.dependency.remove": {"project_ref": fake_ref, "action": {"mode": "preview", "expected_project_fingerprint": fake_fp, "name": "quote"}},
    }
    denied = {}
    for index, (name, arguments) in enumerate(calls.items(), 1):
        response = inspector_call(
            run, environment, f"deny-{index}", denied_args, "tools/call", name,
            arguments, deadline, expected_tool_error=True,
        )
        output = structured(response)
        if output.get("status") != "blocked" or output.get("error_code") != "permission_denied":
            raise RuntimeError(f"inspector_default_deny_{name}")
        denied[name] = output["error_code"]
    return {
        "version": json.loads(INSPECTOR_PACKAGE.read_text())["version"],
        "cli_sha256": sha_file(INSPECTOR),
        "node_sha256": sha_file(NODE),
        "tool_count": len(tools),
        "tool_names": list(EXPECTED_TOOLS),
        "canonical_inventory_sha256": sha_bytes(canonical(tools)),
        "m1_snapshots": unchanged,
        "positive_open": True,
        "default_denials": denied,
        "limitation": "Inspector CLI is one-shot; project references cannot be carried into a later invocation.",
    }


def claude_config(paths: dict[str, Path], socket: str) -> dict:
    return {
        "mcpServers": {
            "rust_engineering": {
                "command": str(SERVER),
                "args": server_args(paths, socket, True),
                "env": {},
            }
        }
    }


def claude_prompt(project: Path) -> str:
    return f"""Qualify the Rust Engineering MCP using only its MCP tools. The authorized scratch project is {project}.
Discover the available MCP tools and use rust.project.open. Then complete these five mutations sequentially, reopening the project after every commit so you always use a current project reference:
1. Add dependency key `quoted` as package `quote`, exact requirement `=1.0.47`, normal dependency, feature `proc-macro`, optional false, default features false. Preview first, inspect the complete returned diff and validation, then commit.
2. Remove exactly dependency key `quoted`. Preview and review the complete diff and validation, commit, then reopen. The lock must return to the std-only state before later operations.
3. Apply a package Rust lint setting `unsafe_code = forbid` with priority omitted (no explicit priority) using rust.manifest.patch. Preview and review, commit, reopen.
4. Apply rust.fmt.apply. Preview and review, commit, reopen.
5. Apply rust.fix.apply to remove the existing unused mut warning. Preview and review, commit, reopen, then retrieve that operation's receipt.
Reference rule for every operation: commit invalidates its input project_ref. Each reopen returns a NEW data.project_ref. Discard the old reference and copy the exact newly returned value into every following call, including the final Fix receipt. Immediately before the final receipt, state which newly returned reference you will use. Never use the reference from Fix preview/commit for its receipt.
Do not call any non-MCP tool. Do not skip a preview or commit. Stop on any blocked, failed, cancelled or unavailable result. Finish with a concise account of the operations and whether every reviewed candidate matched the requested scope."""


def walk_json(value: object):
    yield value
    if isinstance(value, dict):
        for child in value.values():
            yield from walk_json(child)
    elif isinstance(value, list):
        for child in value:
            yield from walk_json(child)


def normalize_tool(name: str) -> str | None:
    if not name.startswith("mcp__rust_engineering__"):
        return None
    suffix = name.removeprefix("mcp__rust_engineering__")
    for expected in ("rust.project.open", *M2_TOOLS):
        if suffix in (expected, expected.replace(".", "_")):
            return expected
    return f"unexpected:{suffix}"


def validate_claude_stream(raw: bytes) -> dict:
    calls = []
    by_id = {}
    results = {}
    models = set()
    events = []
    for line in raw.splitlines():
        if not line.strip():
            continue
        event = json.loads(line)
        events.append(event)
        for value in walk_json(event):
            if not isinstance(value, dict):
                continue
            model = value.get("model")
            if isinstance(model, str) and "claude" in model:
                models.add(model)
            if value.get("type") == "tool_use" and isinstance(value.get("name"), str):
                normalized = normalize_tool(value["name"])
                if normalized is None or normalized.startswith("unexpected:"):
                    raise RuntimeError(f"claude_forbidden_tool_{value['name']}")
                identifier = value.get("id")
                if not isinstance(identifier, str) or identifier in by_id:
                    raise RuntimeError("claude_duplicate_or_missing_tool_use_id")
                call = {"id": identifier, "tool": normalized, "input": value.get("input")}
                calls.append(call)
                by_id[identifier] = call
            if value.get("type") == "tool_result":
                identifier = value.get("tool_use_id")
                if not isinstance(identifier, str) or identifier in results:
                    raise RuntimeError("claude_duplicate_or_missing_tool_result_id")
                results[identifier] = value
    if not events or events[-1].get("type") != "result" or events[-1].get("subtype") != "success" or events[-1].get("is_error") is True:
        raise RuntimeError("claude_missing_success_final_event")
    names = [call["tool"] for call in calls]
    if not models or any(not model.startswith(MODEL) for model in models):
        raise RuntimeError("claude_model_identity_or_fallback")
    for tool in M2_TOOLS:
        modes = [call.get("input", {}).get("action", {}).get("mode") for call in calls if call["tool"] == tool]
        if "preview" not in modes or "commit" not in modes:
            raise RuntimeError(f"claude_missing_preview_commit_{tool}")
    fix_modes = [call.get("input", {}).get("action", {}).get("mode") for call in calls if call["tool"] == "rust.fix.apply"]
    if "receipt" not in fix_modes or names.count("rust.project.open") < 6:
        raise RuntimeError("claude_missing_reopen_or_receipt")
    if set(results) != set(by_id):
        raise RuntimeError("claude_unmatched_tool_results")
    observations = []
    for identifier, call in by_id.items():
        result = results[identifier]
        if result.get("is_error") is True:
            raise RuntimeError(f"claude_failed_tool_result_{call['tool']}")
        candidates = []
        for value in walk_json(result.get("content")):
            if isinstance(value, dict) and isinstance(value.get("structuredContent"), dict):
                candidates.append(value["structuredContent"])
            elif isinstance(value, str):
                try:
                    parsed = json.loads(value)
                except json.JSONDecodeError:
                    continue
                for parsed_value in walk_json(parsed):
                    if isinstance(parsed_value, dict) and "status" in parsed_value:
                        candidates.append(parsed_value)
        outputs = [value for value in candidates if value.get("status") in {"passed", "failed", "blocked", "cancelled", "unavailable"}]
        if len(outputs) != 1 or outputs[0].get("status") != "passed":
            raise RuntimeError(f"claude_nonpassing_or_ambiguous_tool_result_{call['tool']}")
        action = call.get("input", {}).get("action", {})
        mode = action.get("mode") if isinstance(action, dict) else None
        if mode == "commit" and outputs[0].get("data", {}).get("state") != "committed":
            raise RuntimeError(f"claude_commit_not_committed_{call['tool']}")
        if mode == "receipt" and outputs[0].get("data", {}).get("state") != "committed":
            raise RuntimeError(f"claude_receipt_not_committed_{call['tool']}")
        observations.append({"tool_use_id": identifier, "tool": call["tool"], "mode": mode, "status": "passed"})
    return {"calls": calls, "results": observations, "tool_call_count": len(calls), "tool_result_count": len(results), "observed_models": sorted(models), "final_event_subtype": "success"}


def run_claude(run: Path, paths: dict[str, Path], socket: str, deadline: float) -> dict:
    config = run / "claude-mcp.json"
    save_json(config, claude_config(paths, socket))
    allowed = [
        "mcp__rust_engineering__rust.project.open",
        *[f"mcp__rust_engineering__{name}" for name in M2_TOOLS],
        "mcp__rust_engineering__rust_project_open",
        *[f"mcp__rust_engineering__{name.replace('.', '_')}" for name in M2_TOOLS],
    ]
    argv = [
        str(CLAUDE), "--print", "--output-format", "stream-json", "--verbose",
        "--model", MODEL, "--effort", EFFORT, "--no-session-persistence",
        "--restricted", "--setting-sources", "", "--strict-mcp-config",
        "--mcp-config", str(config), "--disable-slash-commands", "--no-chrome",
        "--tools", "", "--allowedTools", ",".join(allowed),
        "--permission-mode", "dontAsk", "--permission-prompts", "none",
        "--system-prompt", "You are a bounded third-party MCP client qualifier. Use only the explicitly configured Rust Engineering MCP server and follow the requested preview-review-commit workflow.",
        claude_prompt(paths["project"]),
    ]
    remaining = int(deadline - time.monotonic())
    if remaining < 1:
        raise RuntimeError("qualification_wall_timeout")
    code, stdout, stderr, duration = run_bounded(
        argv, run, safe_environment(paths["home"]), remaining,
        ARTIFACTS / "claude-model-session.json",
    )
    if code != 0:
        raise RuntimeError(f"claude_exit_{code}:stderr_sha256={sha_bytes(stderr)}")
    stream = validate_claude_stream(stdout)
    actual_tree = snapshot(paths["project"])
    expected_bytes = {"Cargo.toml": FINAL_MANIFEST, "Cargo.lock": LOCK, "src/lib.rs": FINAL_SOURCE}
    expected_tree = {name: sha_bytes(value) for name, value in expected_bytes.items()}
    if actual_tree != expected_tree:
        raise RuntimeError("claude_final_source_mismatch")
    return {
        "version": subprocess.run([str(CLAUDE), "--version"], capture_output=True, text=True, timeout=10, check=True).stdout.strip(),
        "executable_sha256": sha_file(CLAUDE),
        "model_requested": MODEL,
        "effort_requested": EFFORT,
        "fallback_configured": False,
        "builtins": [],
        "allowed_mcp_tools": ["rust.project.open", *M2_TOOLS],
        "duration_seconds": round(duration, 3),
        "stderr_sha256": sha_bytes(stderr),
        "stream": stream,
        "final_tree_sha256": actual_tree,
    }


def docker_inventory(run: Path, socket: str) -> dict[str, list[str]]:
    config = run / "docker-config"
    config.mkdir(exist_ok=True, mode=0o700)
    (config / "config.json").write_text("{}\n")
    inventory = {}
    for kind in ("container", "volume"):
        argv = [str(DOCKER), "--config", str(config), "--host", f"unix://{socket}", kind, "ls"]
        if kind == "container":
            argv += ["--all", "--no-trunc"]
        argv += ["--filter", "label=org.rust-mcp.execution=true", "--format", "{{.Names}}" if kind == "container" else "{{.Name}}"]
        result = subprocess.run(argv, env={}, capture_output=True, text=True, timeout=15, check=True)
        inventory[kind + "s"] = [line for line in result.stdout.splitlines() if line]
    return inventory


def prerequisites() -> dict:
    required = (NODE, INSPECTOR, INSPECTOR_PACKAGE, CLAUDE, SERVER, DOCKER)
    missing = [str(path) for path in required if not path.is_file()]
    if missing:
        raise RuntimeError("missing_prerequisites:" + ",".join(missing))
    version = json.loads(INSPECTOR_PACKAGE.read_text())["version"]
    if version != "2.5.0":
        raise RuntimeError(f"inspector_version_{version}")
    claude_version = subprocess.run([str(CLAUDE), "--version"], capture_output=True, text=True, timeout=10, check=True).stdout.strip()
    if not claude_version.startswith("2.1.260"):
        raise RuntimeError(f"claude_version_{claude_version}")
    (WORK / "tmp").mkdir(parents=True, exist_ok=True, mode=0o700)
    auth = subprocess.run(
        [str(CLAUDE), "auth", "status"],
        env=safe_environment(WORK),
        capture_output=True,
        timeout=10,
    )
    try:
        auth_status = json.loads(auth.stdout)
    except (json.JSONDecodeError, UnicodeDecodeError) as error:
        raise RuntimeError("claude_auth_status_invalid") from error
    if auth.returncode != 0 or auth_status.get("loggedIn") is not True:
        raise RuntimeError("claude_normal_api_auth_unavailable")
    return {
        "inspector_version": version,
        "inspector_cli_sha256": sha_file(INSPECTOR),
        "node_sha256": sha_file(NODE),
        "claude_version": claude_version,
        "claude_sha256": sha_file(CLAUDE),
        "claude_auth_method": auth_status.get("authMethod"),
        "server_sha256": sha_file(SERVER),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--run", action="store_true", help="execute the serialized Docker/model gate")
    parser.add_argument("--docker-socket", default=os.environ.get("RUST_MCP_TEST_SOCKET"))
    options = parser.parse_args()
    identities = prerequisites()
    prepared = {
        "schema": "rust-mcp-m2-third-party-clients-v2",
        "status": "prepared" if not options.run else "running",
        "scope": "Inspector one-shot discovery/default-deny plus one stock Claude model-directed five-tool mutation workflow",
        "limits": {"wall_seconds": WALL_SECONDS, "combined_output_bytes": MAX_OUTPUT},
        "identities": identities,
        "inspector_exit_5_disposition": {
            "installed_source": "target/m1-17-inspector/node_modules/@modelcontextprotocol/inspector/clients/cli/build/index.js",
            "installed_source_sha256": identities["inspector_cli_sha256"],
            "exit_code_definition_lines": "13255-13262",
            "is_error_mapping_lines": "13741-13746",
            "semantics": "Inspector 2.5.0 emits the JSON result, then exits 5 when result.isError is true; only the five expected default-deny calls accept that exit and still require isError:true plus blocked/permission_denied.",
        },
        "expected_tools": list(EXPECTED_TOOLS),
        "expected_model_calls": {
            "rust.project.open": "at least six",
            **{tool: ["preview", "commit"] for tool in M2_TOOLS},
            "rust.fix.apply_receipt": True,
        },
        "security": {
            "claude_restricted": True,
            "builtin_tools": [],
            "strict_mcp_config": True,
            "permission_bypass": False,
            "fallback_model": False,
            "network_claim": "No client network-isolation claim; the normal model API is required. Guest execution remains Docker network=none.",
        },
    }
    save_json(RECEIPT, prepared)
    if not options.run:
        print(RECEIPT)
        return 0
    if not options.docker_socket or not options.docker_socket.startswith("/"):
        raise RuntimeError("explicit_absolute_docker_socket_required")
    run = WORK / f"run-{time.time_ns()}"
    run.mkdir(parents=True, mode=0o700)
    paths = create_fixture(run)
    prepared["run_directory"] = str(run.relative_to(ROOT))
    prepared["fixture_before"] = snapshot(paths["project"])
    prepared["vendor_fingerprint"] = VENDOR_FP
    prepared["docker_before"] = docker_inventory(run, options.docker_socket)
    if any(prepared["docker_before"].values()):
        raise RuntimeError("docker_not_exclusive")
    try:
        deadline = time.monotonic() + WALL_SECONDS
        prepared["inspector"] = inspect_stock_client(run, paths, options.docker_socket, deadline)
        prepared["claude"] = run_claude(run, paths, options.docker_socket, deadline)
        prepared["fixture_after"] = snapshot(paths["project"])
        prepared["docker_after"] = docker_inventory(run, options.docker_socket)
        if any(prepared["docker_after"].values()):
            raise RuntimeError("docker_cleanup_incomplete")
        prepared["status"] = "passed"
        return 0
    except BaseException as error:
        prepared["status"] = "failed"
        prepared["error"] = f"{type(error).__name__}:{error}"
        try:
            prepared["docker_after_failure"] = docker_inventory(run, options.docker_socket)
        except BaseException as inventory_error:
            prepared["docker_inventory_error"] = str(inventory_error)
        raise
    finally:
        save_json(RECEIPT, prepared)
        print(RECEIPT, flush=True)


if __name__ == "__main__":
    raise SystemExit(main())
